### ISSUE TITLE
[FS] EXT2 todo

### ISSUE THREAD

**Issue by NielsDev** [NielsDev/QuLib-OS#1]
There are some things on the TODO list:

- [x] Deleting a file should actually decrease the link count, when it reaches zero, it should be deleted
- [x] unlink: files, rmdir: directories
- [x] Deleting directories
- [x] Increase the inode size when the directory gets an additional block for dirents
- [x] Cleanup the code (with macros)
- [x] Errors
